package require xmlgen
namespace import ::xmlgen::*

declaretag ScapiSocketResponse
declaretag rsp
declaretag registration
declaretag interaction
declaretag ack

buffer ans { ScapiSocketResponse ! { rsp ! { registration ! {} } } }
buffer ok { ScapiSocketResponse ! { rsp ! { interaction ! { ack ! } } } }

set timeout [expr 5 * 60]

spawn netcat -lp 50153

expect "</ScapiSocketRequest>"
send "$ans\r"

expect "</ScapiSocketRequest>"
send "$ok\r"

interact
